version: "3.8"

services:
  npm-db:
    image: mariadb:10.5
    container_name: npm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - npm-db-data:/var/lib/mysql

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "${NPM_HTTP_PORT}:80"
      - "${NPM_HTTPS_PORT}:443"
      - "${NPM_ADMIN_PORT}:81"
    environment:
      DB_MYSQL_HOST: npm-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  whoami:
    image: containous/whoami
    container_name: whoami
    restart: always
    ports:
      - "${WHOAMI_PORT}:80"

  app:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    container_name: flask-app
    restart: always
    environment:
      - LISTEN_PORT=5000
    volumes:
      - ./app:/app
    ports:
      - "${APP_PORT}:5000"

volumes:
  npm-db-data:
  npm-data:
  npm-letsencrypt:
  portainer-data:
